name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:  # Runs "At 01:00 on Monday Tuesday Wednesday Thursday Friday Saturday and Sunday"
    - cron: '0 1 * * 0,1,2,3,4,5,6'

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Run npm run ci
      run: npm ci 
    
    - name: Run actual test
      run: npm test
